
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ABA = 6;
  public static final int ARR = 5;
  public static final int RPAREN = 12;
  public static final int EQUAL = 14;
  public static final int TERMINO = 10;
  public static final int DAVALOR = 7;
  public static final int IZQ = 3;
  public static final int COLOR = 8;
  public static final int DER = 4;
  public static final int LPAREN = 11;
  public static final int POS = 2;
  public static final int ID = 15;
  public static final int EDITAR = 9;
  public static final int COMMA = 13;
  public static final int C = 17;
  public static final int EOF = 0;
  public static final int DIGITO = 16;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "POS",
  "IZQ",
  "DER",
  "ARR",
  "ABA",
  "DAVALOR",
  "COLOR",
  "EDITAR",
  "TERMINO",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "EQUAL",
  "ID",
  "DIGITO",
  "C"
  };
}

